resources:
    - 
        name: flight-school
        type: git
        source:
            uri: git@github.com:gissehel/flight-school.git
            branch: master
            private_key: ((fs-private-key))
    - 
        name: version
        type: semver
        source:
            driver: git
            uri: git@github.com:gissehel/flight-school.git
            branch: master
            file: version
            private_key: ((fs-private-key))

jobs:
    - 
        name: test-app
        plan:
            - 
                get: flight-school
                trigger : true
            -   
                task: tests
                file: flight-school/ci/build.yml
    - 
        name: patch
        serial_groups:
            - version
        plan:
            - 
                get: flight-school
                passed: 
                    - test-app
            - 
                put: version
                params:
                    bump: patch
                    pre: rc
    - 
        name: minor
        serial_groups: 
            - version
        plan:
            - 
                get: flight-school
                passed: 
                    - test-app
            - 
                put: version
                params: 
                    bump: minor
                    pre: rc
    - 
        name: major
        serial_groups: 
            - version
        plan:
            - 
                get: flight-school
                passed: 
                    - test-app
            - 
                put: version
                params: 
                    bump: major
                    pre: rc
    - 
        name: rc
        serial_groups: 
            - version
        plan:
            - 
                get: flight-school
                passed: 
                    - test-app
            - 
                put: version
                params: 
                    pre: rc
    - 
        name: relase
        serial_groups:
            - version
        plan:
            - 
                get: flight-school
                passed:
                    - test-app
            -
                put: version
                params:
                    bump: final
    -
        name: is release
        serial_groups:
            - version
        plan:
            -
                get: flight-school
                trigger : true
                passed:
                    - test-app
            -   
                task: tests
                file: flight-school/ci/is_release.yml
            - 
                put: version
                params:
                    bump: patch
                    pre: rc
                
